// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlBT8_fVGvOcnDSp-lMNCXg-6TaVoxXxw',
    appId: '1:693765995135:web:6ccaae586041d3f96e9d4a',
    messagingSenderId: '693765995135',
    projectId: 'chat-app-8039d',
    authDomain: 'chat-app-8039d.firebaseapp.com',
    storageBucket: 'chat-app-8039d.appspot.com',
    measurementId: 'G-YCB7GTLNJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJLgbmeR_kUpjUmGcL1gOcSifQuEbzF4g',
    appId: '1:693765995135:android:6684159972da40ef6e9d4a',
    messagingSenderId: '693765995135',
    projectId: 'chat-app-8039d',
    storageBucket: 'chat-app-8039d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXqq5dgf0xyjGjv-mrcGSRkdtFkM28m8I',
    appId: '1:693765995135:ios:68387ecdc4c17e666e9d4a',
    messagingSenderId: '693765995135',
    projectId: 'chat-app-8039d',
    storageBucket: 'chat-app-8039d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXqq5dgf0xyjGjv-mrcGSRkdtFkM28m8I',
    appId: '1:693765995135:ios:7d9af424ae372ca86e9d4a',
    messagingSenderId: '693765995135',
    projectId: 'chat-app-8039d',
    storageBucket: 'chat-app-8039d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
